### PR TITLE
Fix linking error because json cpp was not found

### PR DESCRIPTION
**Pull request by Rauldg**
I am not sure if this is always needed, but for my installation it was...

### CODE REVIEW

**Comment by AlexanderFabisch** [comment]
This should not be required. pkg-config is used to find jsoncpp. Sometimes it helps to remove the repository and rebuild everything.

**Comment by Rauldg** [comment]
Without the require, cmake was not setting the path to the json library, 

The trick of removing and rebuilding works sometimes, but what do you mean by everything? The dependencies too?

Actually what I sometimes find, is that the library for instance configmaps build but then a second one using it doesn't because it misses some link that should have happen when building the first:

(1) -> Builds OK, (2 depends on 1) -> Can't build because of missing link that (1) uses internally. 

This is actually what happened in this case, I guess this has something to do with autoproj.

**Comment by malter** [comment]
I agree with Alexander, pkg-config should find json cpp to build the configmaps. Other packages using the configmaps should include json cpp via the configmaps.pc file. I think json cpp is listed there as required.
Can you post the logged error if the build fails?

**Comment by Rauldg** [comment]
The building error was triggering actually in [orogen/mars_addons](https://github.com/rock-simulation/simulation-orogen-mars_addons).

Actually even after removing the line of the CMake it builds now properly, so I don't know where the initial error might have been triggered.

**Pull request closed without merging**
